#!/bin/bash
# TV Tenderr - Setup Script
set -e

echo "🎬 TV Tenderr Setup"
echo "==================="

# Check Python
if ! command -v python3 &> /dev/null; then
    echo "❌ Python3 not found. Install Python 3.10+ first."
    exit 1
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "✅ Python $PYTHON_VERSION found"

# Install Python dependencies
echo "📦 Installing Python dependencies..."
pip3 install --user fastapi uvicorn httpx python-dotenv aiofiles 2>/dev/null || \
pip3 install --break-system-packages fastapi uvicorn httpx python-dotenv aiofiles

# Create .env if it doesn't exist
if [ ! -f .env ]; then
    echo ""
    echo "📝 First-time setup - let's configure your services:"
    echo ""

    # Interactive setup
    read -p "Radarr URL (e.g. http://192.168.1.100:7878): " RADARR_URL
    read -p "Radarr API Key: " RADARR_KEY
    read -p "Sonarr URL (e.g. http://192.168.1.100:8989): " SONARR_URL
    read -p "Sonarr API Key: " SONARR_KEY
    read -p "Plex URL (e.g. http://192.168.1.100:32400): " PLEX_URL
    read -p "Plex Token: " PLEX_TOKEN
    read -p "TMDb API Key (get free at themoviedb.org): " TMDB_KEY
    read -p "Server port [8899]: " PORT
    PORT=${PORT:-8899}

    cat > .env << EOF
# TV Tenderr Configuration
# Generated by setup.sh on $(date)

# Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=$PORT

# Radarr (movies)
RADARR_URL=$RADARR_URL
RADARR_KEY=$RADARR_KEY

# Sonarr (TV shows)
SONARR_URL=$SONARR_URL
SONARR_KEY=$SONARR_KEY

# Plex
PLEX_URL=$PLEX_URL
PLEX_TOKEN=$PLEX_TOKEN

# TMDb (discover feature)
TMDB_KEY=$TMDB_KEY

# Quality defaults (can be changed in app/web settings)
RADARR_QUALITY_ID=4
SONARR_QUALITY_ID=4
RADARR_ROOT_FOLDER=H:\\
SONARR_ROOT_FOLDER=I:\\TV
EOF

    echo ""
    echo "✅ .env created with your settings"
else
    echo "✅ .env already exists"
fi

# Create data directory
mkdir -p data

# Create systemd service file
cat > tv-tenderr.service << EOF
[Unit]
Description=TV Tenderr - Media Library Manager
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$(pwd)
ExecStart=$(which python3) backend.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
EOF

echo ""
echo "==========================="
echo "✅ Setup complete!"
echo "==========================="
echo ""
echo "Start the server:"
echo "  python3 backend.py"
echo ""
echo "Or install as a system service:"
echo "  sudo cp tv-tenderr.service /etc/systemd/system/"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable tv-tenderr"
echo "  sudo systemctl start tv-tenderr"
echo ""
echo "Access points:"
echo "  🌐 Web GUI:   http://localhost:$PORT"
echo "  📱 Android:   Enter http://YOUR_IP:$PORT in the app settings"
echo ""
echo "To change settings later:"
echo "  nano .env"
echo "  # or use the Settings page in the app/web GUI"
